apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: astro
build:
  # tagPolicy:
  #   gitCommit: {}
  local:
    push: true
  artifacts:
    - image: registry.gitlab.com/mkoertgen/devops-toolkit/apps/astro
      docker:
        dockerfile: Dockerfile
deploy: {} # TODO
