---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-go
  namespace: flux-system
spec:
  chart:
    spec:
      chart: hello-go
      sourceRef:
        kind: GitRepository
        name: staging
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.9
    ingress:
      host: hello-go.staging.127.0.0.0.nip.io

