# Tekton katacoda scneario: https://github.com/tektoncd/dashboard/blob/main/docs/walkthrough/walkthrough-oauth2-proxy.md
# oauth2-proxy values reference: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml

# Oauth client configuration specifics
config:
  #--- GitHub ---
  # See https://github.com/settings/developers
  clientID: oauth2-proxy
  clientSecret: proxy

  # https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L23
  # Documentation: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example
  # configFile: |-
  #   email_domains = [ "*" ]
  #   upstreams = [ "file:///dev/null" ]

extraArgs:
  #--- Google ---
  # - https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#google-auth-provider

  #--- GitHub ---
  #provider: github

  #--- Dex (via oidc) -------------------
  # Support for multiple providers is ongoing work, cf.:
  # - https://github.com/oauth2-proxy/oauth2-proxy/issues/926
  # -
  # Meanwhile we might use dexidp for multiple providers
  # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#dex
  provider: oidc
  oidc-issuer-url: http://dex.127-0-0-1.nip.io
  #--- HACK: For local setup using .nip.io -------------------------
  #oidc-issuer-url: http://dex.tools.svc.cluster.local:5556
  #insecure-oidc-skip-issuer-verification: true
  skip-oidc-discovery: true
  # See http://dex.127-0-0-1.nip.io/.well-known/openid-configuration
  login-url: http://dex.127-0-0-1.nip.io/auth
  #redeem-url: http://dex.127-0-0-1.nip.io/token
  #oidc-jwks-url: http://dex.127-0-0-1.nip.io/keys
  redeem-url: http://dex.tools.svc.cluster.local:5556/token
  oidc-jwks-url: http://dex.tools.svc.cluster.local:5556/keys
  #-----------------------------------------------------------------

  #--- Azure ---
  # Azure example (requires https), cf.:
  # - https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#azure-auth-provider
  #provider: azure
  #azure-tenant: <organization/tenant>.onmicrosoft.com
  #provider-display-name: Organization

  #----------------
  whitelist-domain: 127-0-0-1.nip.io
  cookie-domain: 127-0-0-1.nip.io
  redirect-url: http://auth.127-0-0-1.nip.io/oauth2/callback
  cookie-secure: "false"
  #---
  skip-provider-button: true

ingress:
  enabled: true
  path: /
  hosts:
    - auth.127-0-0-1.nip.io
