# https://fluxcd.io/docs/guides/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  #values: # ...
