apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: go-kubebuilder-guestbook
build:
  # tagPolicy:
  #   gitCommit: {}
  artifacts:
    - image: registry.127.0.0.1.nip.io/myapps/go-kubebuilder-guestbook # harbor-core.127.0.0.1.nip.io/myapps/go-kubebuilder-guestbook
      docker:
        dockerfile: Dockerfile
