apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: go-kubebuilder-guestbook
build:
  local:
    push: true
  # tagPolicy:
  #   gitCommit: {}
  artifacts:
    - image: registry.gitlab.com/mkoertgen/devops-toolkit/apps/go-kubebuilder-guestbook
      docker:
        dockerfile: Dockerfile
deploy: {} # TODO
