version: "3.7"

services:
  go-kubebuilder-guestbook:
    image: ${CR_BASE}/go-kubebuilder-guestbook:${GITVERSION_SEMVER:-latest}
    build:
      context: ./_apps/go/src

  astro:
    image: ${CR_BASE}/astro:${GITVERSION_SEMVER:-latest}
    build:
      context: ./_apps/astro
